# Setup:
#   python3 -m venv venv
#   source venv/bin/activate
#   pip install gradio_client opencv-python

import sys
import os
import time
import argparse
from gradio_client import Client, handle_file
import cv2


# ---------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------
parser = argparse.ArgumentParser()
parser.add_argument("inputs", nargs="*", help="Image files to process")
parser.add_argument("--directory", type=str, help="Directory of images")
parser.add_argument("--prompt", type=str, default="person", help="Segmentation prompt")
parser.add_argument("--ip", type=str, default="139.91.185.16")
parser.add_argument("--port", type=str, default="7860")
parser.add_argument("--outdir", type=str, default="output_masks")
parser.add_argument("--start", type=int, default=0)

args = parser.parse_args()


# ---------------------------------------------------------
# Collect input images
# ---------------------------------------------------------
files = []

if args.directory:
    if not os.path.isdir(args.directory):
        print("Directory does not exist:", args.directory)
        sys.exit(1)

    for f in sorted(os.listdir(args.directory)):
        if f.lower().endswith((".jpg", ".png", ".jpeg", ".bmp")):
            files.append(os.path.join(args.directory, f))

files.extend(args.inputs)

if not files:
    print("No input images provided.")
    sys.exit(0)

files = sorted(files)

os.makedirs(args.outdir, exist_ok=True)


# ---------------------------------------------------------
# Connect to Gradio server
# ---------------------------------------------------------
server_url = f"http://{args.ip}:{args.port}"
print("Connecting to:", server_url)

client = Client(server_url)
# client.view_api()  # useful for debugging


# ---------------------------------------------------------
# Process images
# ---------------------------------------------------------
for i in range(args.start, len(files)):
    image_path = files[i]
    print(f"[{i+1}/{len(files)}] Processing:", image_path)

    start_time = time.time()

    try:
        # IMPORTANT:
        # API name is auto-generated by Gradio Interface
        result = client.predict(
            handle_file(image_path),
            args.prompt
        )
    except Exception as e:
        print("Error processing image:", e)
        print("Restart with --start", i)
        break

    elapsed = time.time() - start_time
    print(f"  Done in {elapsed:.2f}s")

    # -----------------------------------------------------
    # Save returned binary mask
    # -----------------------------------------------------
    # result is a single image path (binary mask)
    mask_path = result

    mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
    if mask is None:
        print("Failed to load returned mask:", mask_path)
        continue

    out_name = os.path.splitext(os.path.basename(image_path))[0] + "_mask.png"
    out_path = os.path.join(args.outdir, out_name)

    cv2.imwrite(out_path, mask)
    print("  Saved mask ->", out_path)


print("Done.")

